apiVersion: v1
kind: Service
metadata:
  name: {{ include "trackward.fullname" . }}-gateway
  labels:
    {{- include "trackward.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - name: http
      port: {{ .Values.gateway.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "trackward.gateway.selectorLabels" . | nindent 4 }}
